#!/bin/bash
# if we don't have a file, start at zero
if [ ! -f "/tmp/bluetooth_mode.dat" ] ; then
  bluetooth_mode="off"
else
  bluetooth_mode=`cat /tmp/bluetooth_mode.dat`
fi

if [ $bluetooth_mode = "off" ]; then
  sudo systemctl start bluetooth.service
  if [ $? -eq 0 ]; then
    bluetooth_mode="on"
  fi
else
  sudo systemctl stop bluetooth.service
  if [ $? -eq 0 ]; then
    bluetooth_mode="off"
  fi
fi

echo "bluetooth: ${bluetooth_mode}"
echo "${bluetooth_mode}" > /tmp/bluetooth_mode.dat
