#!/bin/bash
# if we don't have a file, start at zero
if [ ! -f "/tmp/vpn_mode.dat" ] ; then
  vpn_mode="off"
else
  vpn_mode=`cat /tmp/vpn_mode.dat`
fi

if [ $vpn_mode = "off" ]; then
  # Old vpn
  #sudo systemctl start stunnel
  #sudo openvpn --daemon --auth-nocache --cd "/home/cousine/projects/vpn/keys" --config "secure.ovpn"
  sudo nmcli connection up cousine-wireguard-vpn
  if [ $? -eq 0 ]; then
    vpn_mode="on"
  fi
else
  #sudo systemctl stop stunnel.service
  #sudo killall openvpn
  sudo nmcli connection down cousine-wireguard-vpn
  if [ $? -eq 0 ]; then
    vpn_mode="off"
  fi
fi
echo "VPN: ${vpn_mode}"
echo "${vpn_mode}" > /tmp/vpn_mode.dat
