# tzfn theme
theme_black="#121414"
theme_blue="#558ba6"
theme_yellow="#ffaf0a"
theme_red="#f84a12"
theme_white="#d6d9e0"
theme_green="#36994e"
theme_visual_grey="#969399"
theme_comment_grey="#646266"
theme_bg="#17191a"
theme_accent="#ffaf0a"
theme_primary="#17191a"
