#!/bin/bash
# if we don't have a file, start at zero
if [ ! -f "/tmp/vpn_mode.dat" ]; then
	vpn_mode="off"
else
	vpn_mode=$(cat /tmp/vpn_mode.dat)
fi

if [ $vpn_mode = "off" ]; then
	sudo wg-quick up /Users/cousine/Projects/vpn/payrails.conf
	if [ $? -eq 0 ]; then
		vpn_mode="on"
	fi
else
	sudo wg-quick down /Users/cousine/Projects/vpn/payrails.conf
	if [ $? -eq 0 ]; then
		vpn_mode="off"
	fi
fi
echo "VPN: ${vpn_mode}"
echo "${vpn_mode}" >/tmp/vpn_mode.dat
