set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "left"
set-option -g status-left-length 80
set-option -g status-right-length 90
set-option -g status-bg $theme_bg
set-window-option -g window-status-style none
set-window-option -g window-status-format "#[fg=$theme_visual_grey, bg=$theme_bg] #I:#W"
set-window-option -g window-status-current-format "#[bg=$theme_bg]  #[fg=$theme_primary, bg=$theme_accent, bold][#I:#W:#{?#{&&:#{!=:#{pane_title},#{host}},#{!=:#{pane_title},}},#{pane_title},#{pane_current_command}}#{?window_zoomed_flag, 🔍,}]"
set-window-option -g window-status-activity-style "bg=$theme_black, fg=$theme_white"
set-option -g pane-border-style fg=$theme_visual_grey
set-option -g pane-active-border-style fg=$theme_accent
set-option -g message-style "fg=$theme_white, bg=$theme_accent"

set-hook -g window-pane-changed "if-shell -F '#{&&:#{==:#{window_zoomed_flag},0},#{e|>:#{window_panes},1}}' \
    'set-option -w pane-border-status top; set-option -w pane-border-format \"$pane_border_format\"' \
    'set-option -w pane-border-status off'"

set-hook -g window-layout-changed "if-shell -F '#{&&:#{==:#{window_zoomed_flag},0},#{e|>:#{window_panes},1}}' \
    'set-option -w pane-border-status top; set-option -w pane-border-format \"$pane_border_format\"' \
    'set-option -w pane-border-status off'"
