# Sonokai Andromeda Color
theme_black="#181a1c"
theme_blue="#6dcae8"
theme_yellow="#edc763"
theme_red="#fb617e"
theme_white="#ffffff"
theme_green="#9ed06c"
theme_visual_grey="#7e8294"
theme_comment_grey="#5a5e7a"
theme_bg="#3f445b"
theme_accent="#bb97ee"
theme_primary="#6621c9"
